### ISSUE TITLE
Add documentation where templates are stored

### ISSUE THREAD

**Issue by Arvengeance** [barmac/templates-plugin#5]
Creating templates works - but I cannot find the jsons. Where are templates stored?

Using Camunda Modeler 5.2

**Comment by barmac** [comment]
Hi,

the templates are stored in the `config.json` file which is placed in [the user data directory](https://docs.camunda.io/docs/components/modeler/desktop-modeler/search-paths/#user-data-directory). I've added a section on this to the readme.
